### ISSUE TITLE
radiation test -RadBreakout segfault on Cori

### ISSUE THREAD

**Issue by Saligiare-pwd** [AMReX-Astro/Castro#2088] opened 2022-03-08 12:43 UTC
Hallo, I need help running Castro on cori.
I just installed Castro and hypre(2.24) in my home directory on cori haswell. 
When running hydro test, things go well, but when I run radiation test:   
I do the following:
1. module swap PrgEnv-{intel,gnu} 
cd to hyper_dir: ./configure CC=cc CXX=CC FC=ftn then make install
2. export hypre_dir in ~/.bashrc
3. cd to /RadBreakout then make
4.  sbatch with 2 nodes * 4 tasks: srun --cpu_bind=cores ./Castro1d.gnu.haswell.MPI.ex inputs.1d.test
5. Error Message:
  1 MPI initialized with 8 MPI processes
  2 MPI initialized with thread support level 3
  3 AMReX (22.03-8-g6bbcbbb78299) initialized
  4 Segfault
  5 
  6 Starting run at 09:05:32 UTC on 2022-03-08.
  7 Successfully read inputs file ...
  8 
  9 Castro git describe: 22.03-dirty
 10 AMReX git describe: 22.03-8-g6bbcbbb78
 11 Microphysics git describe: 22.03
 12 
 13 radiation initialized, nGroups = 1
 14 reading extern runtime parameters ...
 15 1 Species:
 16 X
 17 2 Auxiliary Variables:
 18 Ye  invmu
 19 Radiation::nGroups = 1
 20 Successfully read inputs file ...
 21 reading initial model
 22 514 points found in the initial model
 23 5 variables found in the initial model file
 24 ^[[1m^[[33m[WARNING] pressure not provided in inputs file^[[0m
 25 ^[[1m^[[33m[WARNING] X not provided in inputs file^[[0m
 26 Castro::numpts_1d at level  0 is 102400
 27 Setting the gravity type to MonopoleGrav
 28 Segfault
 29 Segfault
 30 Segfault...

Other radiation tests also fail as segfault.
Below are modules I've loaded:
  1) modules/3.2.11.4
  2) altd/2.0
  3) darshan/3.2.1
  4) craype-network-aries
  5) gcc/8.3.0
  6) craype/2.6.2
  7) cray-mpich/7.7.10
  8) craype-haswell
  9) craype-hugepages2M
 10) cray-libsci/19.06.1
 11) udreg/2.3.2-7.0.1.1_3.61__g8175d3d.ari
 12) ugni/6.0.14.0-7.0.1.1_7.63__ge78e5b0.ari
 13) pmi/5.0.14
 14) dmapp/7.1.1-7.0.1.1_4.72__g38cf134.ari
 15) gni-headers/5.0.12.0-7.0.1.1_6.46__g3b1768f.ari
 16) xpmem/2.2.20-7.0.1.1_4.28__g0475745.ari
 17) job/2.2.4-7.0.1.1_3.55__g36b56f4.ari
 18) dvs/2.12_2.2.167-7.0.1.1_17.11__ge473d3a2
 19) alps/6.6.58-7.0.1.1_6.30__g437d88db.ari
 20) rca/2.2.20-7.0.1.1_4.74__g8e3fb5b.ari
 21) atp/2.1.3
 22) PrgEnv-gnu/6.0.5
Are there things I missed or get wrong?
Thank you very much!

**Comment by zingale** [comment] 2022-03-08 13:01
what happens if you use the hypre provided by NERSC instead of installing your own?
See the directions here:
https://amrex-astro.github.io/workflow/nersc-compilers.html#hypre

**Comment by zingale** [comment] 2022-03-08 14:15
okay, it looks like the version of hypre there is too old.  

One option would be for you to request that NERSC build a later version of hypre for Cori.

Alternately, if you did build it yourself, I suspect that it was not compiled correctly. Can you try running a pure hypre test problem with your build to make sure that the library was built correctly?

**Comment by Saligiare-pwd** [comment] 2022-03-08 15:09
Dear @zingale ,
1. I will request nersc to build a later version.
2. I can run pure hypre test provided in hypre/src/test with srun
3.  I just re-built Castro and Hypre in $SCRATCH (also update export XXX_DIR...), but still get same error.

**Comment by zingale** [comment] 2022-03-08 15:10
okay thanks.  I will try to reproduce this with a build later today

**Comment by Saligiare-pwd** [comment] 2022-03-09 05:28
Thank you, I will update if I succeed.

**Comment by Saligiare-pwd** [comment] 2022-03-18 05:11
Cori have updated hypre version in e4s:
 module load e4s/22.02
 module load hypre/... (remember to check HYPRE_DIR..)
I have tried hypre 2.23 and 2.24, but still get Segfault.
Would you mind giving me some suggestions?
Thank you!

**Comment by zingale** [comment] 2022-03-18 13:35
thanks, I will try to take a look this weekend.  I am not sure what the issue might be.  We test nightly on local machines, and Castro + hypre + radiation work well in the test suite, so there must still be a NERSC issue somehow.

**Comment by zingale** [comment] 2022-03-20 13:48
The good news is that I was able to get one of the AMReX tutorials (`amrex-tutorials/ExampleCodes/LinearSolvers/ABecLaplacian_C`) to build and run with hypre on Cori using the default Intel compilers and the package: `hypre/2.24.0-intel-19.1.2.254`

```
module load hypre/2.24.0-intel-19.1.2.254
export HYPRE_DIR=$HYPRE_ROOT
```

The bad news is that Castro no longer seems to compile with the intel compilers since the Cori upgrade a few days ago.  There is a problem with one of the header files, so I am not sure what is going on there.

Those hypre libraries seem to require Intel compilers as well.

**Comment by Saligiare-pwd** [comment] 2022-03-23 07:15
Thank you!
I am asking Cori if they can provide a gnu-Hypre.
I will keep figuring out some way to run radiation problems.

**Comment by zingale** [comment] 2022-04-15 12:08
@Saligiare-pwd can you try with this fix that was just merged?

**Comment by Saligiare-pwd** [comment] 2022-04-16 00:10
@zingale yes, I will try later this day!
Thank you all!

**Comment by Saligiare-pwd** [comment] 2022-04-16 03:51
@zingale @maxpkatz Thank you very much! 
This merged seems to fix segfault, however I receive illegal instruction

Regridding radiation object at level 0...
                                         done
habec.verbose                   = 2 
habec.verbose_threshold         = 0 
srun: error: nid12969: tasks 4-7: Illegal instruction
srun: launch/slurm: _step_signal: Terminating StepId=57736641.0
srun: error: nid12968: tasks 0-3: Illegal instruction
srun: error: nid12971: tasks 12-15: Illegal instruction
srun: error: nid12970: tasks 8-11: Illegal instruction

I also updated Microphysics and amrex. 
What have I missed?

**Comment by Saligiare-pwd** [comment] 2022-07-27 06:15
Kind of solve this issue with the current version of own hypre
1. module add gcc/8.3.0
2. In hypre/src: ./configure cc=CC cxx=CC FC=ftn

**Comment by zingale** [comment] 2022-07-28 13:51
great.  I'll close this for now then.  Feel free to reopen if the issue pops up again.

**Closed by zingale** 2022-07-28 13:51 UTC
