### ISSUE TITLE
hybrid momentum appears broken

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#462] opened 2018-12-17 18:26 UTC
running the `rotating_torus` problem with the default `USE_HYBRID_MOMENTUM=TRUE` gives (using `inputs_3d` after 200 steps):

![plt_00200_hybrid_density](https://user-images.githubusercontent.com/7817509/50106954-3f316200-01ff-11e9-8e28-51c5c11d6d72.png)

without the hybrid momentum enabled, we get the more reasonable looking:

![plt_00200_density](https://user-images.githubusercontent.com/7817509/50106979-4e181480-01ff-11e9-95bd-30d92ed661ae.png)

**Comment by zingale** [comment] 2018-12-17 18:33
nevermind... this is the whole point of this problem.  Without explicitly doing the angular momentum conservation approach, we get an instability which disrupts the torus.

**Comment by maxpkatz** [comment] 2019-04-07 10:21
Reopening because hybrid_hydro does appear broken for wdmerger. @guadabsb15 has shown that the stars get weirdly deformed, and I can see that angular momentum is not even close to conserved (running normally conserves angular momentum much better by comparison). Reproducer in wdmerger/tests/wdmerger_3D:

```
mpirun -np 4 ./Castro3d.gnu.MPI.OMP.ex inputs_test_wdmerger_3D castro.do_rotation=0 castro.hybrid_hydro=1 amr.max_level=0 max_step=100000 stop_time=1.0 castro.sum_interval=1 geometry.prob_lo=-2.56e9 -2.56e9 -2.56e9 geometry.prob_hi=2.56e9 2.56e9 2.56e9 castro.init_shrink=0.01 amr.n_cell=64 64 64 castro.do_sponge=0
```

For this setup, the run with hybrid hydro loses 25% of its angular momentum over 1 second of evolution, while the run without using hybrid hydro conserves angular momentum to better than 0.1%.

There's also an issue with the sponge enabled for this problem where the timesteps get very small.

**Comment by maxpkatz** [comment] 2019-04-07 23:30
Angular momentum is conserved if all the source terms (including gravity) are turned off.

**Comment by maxpkatz** [comment] 2019-04-08 00:58
The angular momentum conservation issue is fixed in commit 8d66bc13. There was a typo in the routine that converted linear momentum source terms to hybrid momentum source terms that specifically messed up the angular momentum term. Now for the test problem mentioned above, angular momentum is conserved to 1.e-7 (this is the expected level given the tolerance of the gravity solve).

Hopefully @guadabsb15 can confirm that this resolves the issues she is seeing in her binary WD simulations.

**Comment by maxpkatz** [comment] 2019-04-08 01:01
There still seems to be an issue with the sponge that I have to work out.

**Comment by maxpkatz** [comment] 2019-04-08 05:14
There was an issue with the sponge: we were adding to the local source term rather than setting it, so the results after multiple loop iterations made no sense. (Rotation also had this problem, and I'm betting it explains why there were different answers for the GPU and CPU for the rotating_torus problem.) Now at least the wdmerger problem runs with the sponge on and castro.hybrid_hydro = 1. However, the timesteps start getting pretty small soon after initialization with the sponge on: I'm not sure if this is a bug or just an unfortunate bad interaction between the hybrid hydro and the sponge.

**Comment by maxpkatz** [comment] 2019-04-13 16:42
Closing since I believe #594 has resolved this.

**Closed by maxpkatz** 2019-04-13 16:42 UTC
