### ISSUE TITLE
RadSourceTest does not give the right answer

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#1539] opened 2021-01-13 18:58 UTC
If we run RadSourceTest using the current version of the code, we do not match the analytic solution.  Note: we need to use PR #1538 

We also make sure that we run with `castro.do_hydro = 0`.

To compare against the analytic solution, follow the instructions in `Verification/verification.txt`

**Comment by zingale** [comment] 2021-01-13 18:59
For reference, here's the test output from 20.01, and we see excellent agreement:
![radiating_source](https://user-images.githubusercontent.com/7817509/104496845-825d8b00-55a7-11eb-88a6-e0dbb2b45893.png)

**Comment by zingale** [comment] 2021-01-13 19:41
it is broken on `20.06`

**Comment by zingale** [comment] 2021-01-13 19:48
also broken in `20.03`

**Comment by zingale** [comment] 2021-01-13 23:24
note that 20.02 is also broken.  So the problem arises between 20.01 and 20.02.

**Comment by maxpkatz** [comment] 2021-01-22 02:43
This first goes wrong in commit 0bac4148ae1c35480969d2c2957ea3f40c7dee3a.

**Comment by maxpkatz** [comment] 2021-01-22 04:25
The problem in that specific commit looks like it's that the code in Radiation.cpp overrode to `do_real_eos = 0` if the problem is setting `radiation.const_c_v` in the inputs file, but this override didn't make it to the Fortran which at that time actually implemented the EOS and temperature related stuff. (And it only became a problem in this change because we also moved do_real_eos to become an automatically managed parameter at the same time, which means this override happens after the set to Fortran.)

**Comment by maxpkatz** [comment] 2021-01-22 05:20
And following up on that, the actual problem is that this should have been switched over to the `rad_power_law` EOS which is the one that enforces a constant `c_v`. So #1538 is backwards, we need to remove `eos_gamma` and keep `eos_const_c_v`, but update the Makefile for the right EOS.

**Comment by maxpkatz** [comment] 2021-05-21 23:27
#1534 has the fix described above. Additionally there was one other error which is that the `rad_power_law` opacity module incorrectly applied the floor on kappa to the Planck mean when it was only ever intended to apply to the Rosseland mean; this is addressed in starkiller-astro/Microphysics#673.

**Comment by zingale** [comment] 2021-05-21 23:46
plot from current development:

![radsource](https://user-images.githubusercontent.com/7817509/119207728-44003d00-ba6d-11eb-9db3-f9dfe9304992.png)

**Closed** 2021-05-21 23:46 UTC
