### ISSUE TITLE
changes in temperature behavior? 

### ISSUE THREAD

**Issue by guadabsb15** [AMReX-Astro/Castro#96] opened 2017-01-19 21:16 UTC
I observed the Temp field changing from November to the present running the same setup. I don't see appreciable changes in other fields like density and magvel at the same simulation time.  

Based on the test suite list in  (Castro/Util/regression_testing/hash_pairings.txt),  the two changes were introduced on date 2016-12-01-001 and 2017-01-10-001.  The following table shows the Temp field before this changes and then at each of the previous dates in chronological order.  

  with reflux  |  update_sources_after_reflux = 0  | do_reflux = 0
:---------------:|:---------------------------------------------:|:-----------------:
![plt00060_temp](https://cloud.githubusercontent.com/assets/11277593/22123698/9d885ef0-de5a-11e6-9e16-d2c6f67c12e0.png) | ![plt00060_temp](https://cloud.githubusercontent.com/assets/11277593/22123710/aca0d91c-de5a-11e6-9bbc-0a108e9751aa.png)|![plt00060_temp](https://cloud.githubusercontent.com/assets/11277593/22123724/bc27e696-de5a-11e6-9f00-c1a99ed16b31.png)
|![plt00060_temp](https://cloud.githubusercontent.com/assets/11277593/22123816/3133fd12-de5b-11e6-9381-cab5dc6994ed.png)| ![plt00060_temp](https://cloud.githubusercontent.com/assets/11277593/22123827/3bce8c2e-de5b-11e6-82d7-303d206ddad3.png)|![plt00060_temp](https://cloud.githubusercontent.com/assets/11277593/22123832/4748c272-de5b-11e6-817e-9f8161f0bde1.png)|
|![plt00060_temp](https://cloud.githubusercontent.com/assets/11277593/22123987/ebcc05c0-de5b-11e6-8bc6-9c7c4941529c.png)|![plt00060_temp](https://cloud.githubusercontent.com/assets/11277593/22123999/f65b87b8-de5b-11e6-8bca-6490469ca7ae.png)|![plt00060_temp](https://cloud.githubusercontent.com/assets/11277593/22124011/0052f508-de5c-11e6-9709-7095aad5c142.png)

The details of the two dates are:
1. 2016-12-01-001 
- Castro git hash: 8f17e0c8bd7209fc0567bb935171c01ff66e7f64
- BoxLib git hash: 3b82103657a52b7fce8ad6ac5d5743a931c92596 
- Microphysics git hash: ccc4cdc6d8f12b7ea5641cca5adaf433b8d22e02

2. 2017-01-10-001
- Castro git hash: 9b976b30de6c692aa070f2fce220d46a55eea521 
- BoxLib git hash: 12fe9c19a66d0a7b68466f2a8915f3f689ea9f51
- Microphysics git hash: e0fb64711aec4fe63208d2efb7cdbafbfb452b49

**Comment by zingale** [comment] 2017-01-20 15:08
my experiementation.

Results look bad as shown above when using Castro 16.12 together with _current_ BoxLib and Microphysics

Results look good when using the version from just 5 days earlier, af6370b, with _current_ BoxLib, and older Microphysics  (037b1ce).  We need the older Microphysics to compile.

Good news is that we can use the latest BoxLib for all this testing -- it is not the culprit.

**Comment by zingale** [comment] 2017-01-20 18:28
I can confirm that the badness that shows up at C-F interface around early Dec. occurs to this change:

```
commit 862ab80e25d884641557228a972f2e115d7604f6                                                                                                                                           
Author: Max Katz <maximilian.katz@stonybrook.edu>                                                                                                                                         
Date:   Fri Nov 25 17:56:39 2016 -0500                                                                                                                                                    
                                                                                                                                                                                          
    clean_state now calls computeTemp   
```

If I run after that, it looks bad.  If I manually revert that one-line change in the source after that point, it looks great again.

Additionally, fixing the bug of leaving this out of the other `clean_state` does not fix things.

**Comment by zingale** [comment] 2017-01-20 18:46
Here's an easy way to confirm this:

* checkout the latest Castro
* compile in `Castro/Exec/science/bwp-rad` as:
```
make DIM=2 -j 4 COMP=gnu USE_RAD=FALSE DEBUG=FALSE
```
* run as:
```
mpiexec -n 4 ./Castro2d.gnu.MPI.ex inputs_2d
```

If you do this, you'll see the artifacts at C-F interfaces.

But... modify `Castro.cpp` and comment out the `computeTemp` lines in both `clean_state` routines, and it goes away

**Comment by zingale** [comment] 2017-01-20 19:19
Some plots.(all put on the same scale)

1. current development:

![plt00060_temp_current](https://cloud.githubusercontent.com/assets/7817509/22162089/2a4b5ba6-df1b-11e6-8dbd-306affd586e7.png)

2. current development but with `computeTemp` commented out in both `clean_state`s:

![plt00060_temp_current_wo_computetemp(https://cloud.githubusercontent.com/assets/7817509/22162111/43284e18-df1b-11e6-8566-487559d919d5.png)

3. current development, with `computeTemp` in `clean_state`, but with the call to `reset_internal_energy` in `computeTemp` commented out:

![plt00060_temp](https://cloud.githubusercontent.com/assets/7817509/22162144/68fb9ff0-df1b-11e6-9ed9-4a4fa8b52d0f.png)

**Comment by zingale** [comment] 2017-01-20 19:55
also note that running the code from 16.10 looks great (you need to copy the inputs, probin, and model file from development)

**Comment by zingale** [comment] 2017-01-22 01:56
from Max:

> I also discovered that in the current version of the code, the problem goes away if you set castro.dual_energy_eta2 = 1.0. This has the effect of never resetting the internal energy to be equal to (total - kinetic). I assume one does not need to be so extreme, but I didn't test intermediate values relative to the default (1.e-4).

**Comment by zingale** [comment] 2017-09-02 17:19
closing for now, since this problem is not active at the moment

**Closed by zingale** 2017-09-02 17:19 UTC
Labels: wontfix
