### ISSUE TITLE
NaNs in the rho_E component when using flux limiter

### ISSUE THREAD

**Issue by KiranEiden** [AMReX-Astro/Castro#441] opened 2018-11-15 16:14 UTC
When running the 2D  flame_wave problem on 12 nodes (288 cores) on Edison, I got a crash with the following error at timestep 3900:

```
Calculating diffusion term at time 0.0002766039026

amrex::Abort::285::State has NaNs in the rho_E component::check_for_nan() !!!

SIGABRT

Segfault
```
The run was using a 768 by 192 grid with 2 levels of refinement (by factors of 4 and 2), and had the flux limiter turned on (castro.limit_fluxes_on_small_dens = 1) and a CFL of 0.7. 

These were the inputs and probin files for the run:

[inputs_2d.boost25-4.aprox13](https://github.com/AMReX-Astro/Castro/files/2586122/inputs_2d.boost25-4.aprox13.txt)
[probin.boost25-4.aprox13](https://github.com/AMReX-Astro/Castro/files/2586120/probin.boost25-4.aprox13.txt)

The checkpoint file from one step before the crash may be found here: bender.astro.sunysb.edu:/home/common/flame_wave_25-4_20cm/chk03899

**Comment by maxpkatz** [comment] 2018-11-23 22:47
Are you on a side branch? flame_wave in development branch doesn't have an interp_BC option, so the fortin namelist is not accepted.

**Comment by zingale** [comment] 2018-11-23 23:03
I removed the `interp_BC` option recently.  It was never used.  So this should run on development.  There were 1 or 2 other params that were old, and have been removed.

**Comment by zingale** [comment] 2019-01-29 19:31
closing this since we fixed a bug in the flux limiter and we also no longer discontinuously turn off diffusion, so this is not reproducible anymore.

**Closed by zingale** 2019-01-29 19:31 UTC
