### ISSUE TITLE
amrex::Error::0::Error: initial data has rho <~ small_dens !!!

### ISSUE THREAD

**Issue by zams2cc** [AMReX-Astro/Castro#2762] opened 2024-02-28 08:43 UTC
Following the steps to test the code ,I met some faluts.

./Castro3d.gnu.MPI.ex  inputs-sod-x
...
amrex::Error::0::Error: initial data has rho <~ small_dens !!!
...

**Comment by zingale** [comment] 2024-02-28 21:40
can you provide more information?

what does 

```./Castro3d.gnu.MPI.ex --describe```

show?  (give the full output)

**Comment by zams2cc** [comment] 2024-02-29 06:05
./Castro2d.gnu.ex --describe
==============================================================================
 Castro Build Information
==============================================================================
build date:    2024-02-29 13:51:11.268214
build machine: Linux wq 6.5.0-21-generic #21~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb  9 13:32:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
build dir:     /home/wq/Documents/Castro/Exec/hydro_tests/Sedov
AMReX dir:     /home/wq/Documents/Castro/external/amrex

COMP:          gnu
COMP version:  13.1.0

C++ compiler:  g++
C++ flags:     -Werror=return-type -gdwarf-4 -O3 -std=c++17  -pthread   -DBL_NO_FORT -DAMREX_GPU_MAX_THREADS=0 -DBL_SPACEDIM=2 -DAMREX_SPACEDIM=2 -DBL_FORT_USE_UNDERSCORE -DAMREX_FORT_USE_UNDERSCORE -DBL_Linux -DAMREX_Linux -DAMREX_DIMENSION_AGNOSTIC -DNDEBUG -DAMREX_NO_PROBINIT -DSPONGE -DSTRANG -DSCREEN_METHOD=SCREEN_METHOD_screen5 -DNAUX_NET=0 -Itmp_build_dir/s/2d.gnu.EXE -I. -I/home/wq/Documents/Castro/external/amrex/Src/Base -I/home/wq/Documents/Castro/external/amrex/Src/Base/Parser -I/home/wqDocuments/Castro/external/amrex/Src/AmrCore -I/home/wq/Documents/Castro/external/amrex/Src/Amr -I/home/wq/Documents/Castro/external/amrex/Src/Boundary -I/home/wq/Documents/Castro/external/Microphysics/util -I/home/wq/Documents/Castro/external/Microphysics/util/gcem/include -I./ -I/home/wq/Documents/Castro/Source/driver -I/home/wq/Documents/Castro/Source/hydro -I/home/wq/Documents/Castro/Source/problems -I/home/wangqing/Documents/Castro/Source/sources -I/home/wq/Documents/Castro/external/Microphysics/EOS -I/home/wq/Documents/Castro/external/Microphysics/EOS/gamma_law -I/home/wqDocuments/Castro/external/Microphysics/networks/general_null -I/home/wq/Documents/Castro/external/Microphysics/EOS -I/home/wq/Documents/Castro/external/Microphysics/networks -I/home/wq/Documents/Castro/external/Microphysics/interfaces -I/home/wq/Documents/Castro/external/Microphysics/constants -Itmp_build_dir/castro_sources/2d.gnu.EXE -I/home/wq/Documents/Castro/external/amrex/Tools/C_scripts 

Fortran comp:  gfortran
Fortran flags: -g -O3 -ffree-line-length-none -fno-range-check -fno-second-underscore -fimplicit-none 

Link flags:    -L. 
Libraries:       

EOS: /home/wq/Documents/Castro/external/Microphysics/EOS/gamma_law
NETWORK: /home/wq/Documents/Castro/external/Microphysics/networks/general_null

Castro       git describe: 24.02-1-g1f3bfff97-dirty
AMReX        git describe: 24.02
Microphysics git describe: 24.02
---------------------------------------------------------------------------------------------------------------------------
./Castro2d.gnu.ex inputs.2d.cyl_in_cartcoords

Initializing AMReX (24.02)...
AMReX (24.02) initialized

Starting run at 05:52:27 UTC on 2024-02-29.
Successfully read inputs file ... 

Castro git describe: 24.02-1-g1f3bfff97-dirty
AMReX git describe: 24.02
Microphysics git describe: 24.02

reading extern runtime parameters ...
1 Species: 
X  
Successfully read inputs file ... 
Initializing the data at level 0
amrex::Error::0::Error: initial data has rho <~ small_dens !!!
SIGABRT
See Backtrace.0 file for details
-------------------------------------------------------------------------------------------------------------------------------

It works well on another ubuntu.

**Comment by zingale** [comment] 2024-02-29 12:30
The Castro git hash indicates that you made local changes to the code -- what did you change?  What does `git diff` show?

**Comment by zingale** [comment] 2024-04-05 14:19
closing this since we cannot reproduce.  Feel free to reopen if the problem persists

**Closed by zingale** 2024-04-05 14:19 UTC
