### ISSUE TITLE
temperature behavior worsened in some problems with PR #368

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#398] opened 2018-09-18 16:38 UTC
For this problem:

http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2018-08-13/Sod_stellar-test1-2d.html

the temperature now looks bad behind the contact.  It was nice the day before.  The change is due to #368   

This should be investigated more.

**Comment by maxpkatz** [comment] 2019-02-03 05:50
This seems to have been a contingent effect of the change to the dual-energy behavior. The reason for this is that the temperature floors during the simulation behind the shock. Here is the temperature after step 14:
![temp_14](https://user-images.githubusercontent.com/8052594/52173191-fd6b6500-2733-11e9-837f-208fc8b77b27.png)
and here is the temperature after step 15:
![temp_15](https://user-images.githubusercontent.com/8052594/52173192-03f9dc80-2734-11e9-8126-20d244c0b69e.png)
The blip behind the shock in step 14 has a low temperature (6e7 K). The flooring zone is the one just to the right of it, which starts out at T = 1.5e8 K but then floors down to 1e3 K. From looking at the output, the value for internal energy is at least in the right ballpark, so this zone must have been edged out of the zone of convergence in the EOS.

Increasing small_temp to 1.e6, so that the flooring is less severe, does not help here.

**Comment by maxpkatz** [comment] 2019-02-03 06:17
Using castro.allow_small_energy = 0, which detects this condition and resets the internal energy using the old value of the temperature, results in behavior that is better, but still not great, at the end of the run.
![no_small_energy](https://user-images.githubusercontent.com/8052594/52173373-3e657880-2738-11e9-91af-696b828eb55a.png)

**Comment by maxpkatz** [comment] 2019-02-03 07:37
There was flooring in the old code too, actually. But in compute_temp we had:
```
! In case we've floored, or otherwise allowed the energy to change, update the energy accordingly.

if (dual_energy_update_E_from_e == 1) then
  state(i,j,k,UEDEN) = state(i,j,k,UEDEN) + (state(i,j,k,URHO) * eos_state % e - state(i,j,k,UEINT))
endif
```
Additionally, we used to have `eos_input_is_constant = F` by default. These two effects combined to erase the flooring after about 10 steps, recovering the reasonable-looking profile by the end of 91 steps. If I revert both of these, I can recover the old behavior in development.

**Comment by maxpkatz** [comment] 2019-02-03 18:33
By contrast, we have discovered that the 4th order result with half the resolution is similar to the 2nd order result, which is sensible. So I'm going to close this as not a bug.

We could still investigate techniques for avoiding flooring in the future though.

**Comment by zingale** [comment] 2019-02-03 18:34
for posterity, here's the 4th order SDC solution with 64 zones
![sod_stellar_test1_sdc4_64](https://user-images.githubusercontent.com/7817509/52180760-60064480-27b8-11e9-8eca-5714639ffc04.png)

**Closed by maxpkatz** 2019-02-03 18:33 UTC
