### ISSUE TITLE
Failed to run the Sedov example on NVIDIA A100 GPU

### ISSUE THREAD

**Issue by Jokeren** [AMReX-Astro/Castro#1584] opened 2021-03-05 21:04 UTC
### Configs:

> USE_MPI = TRUE
> USE_OMP = FALSE
> USE_CUDA = TRUE
> CUDA_ARCH = 80

### Compilers:

- nvcc 11.2
- gcc 8.3.1

### Command:

`mpirun -np 1 ./Castro2d.gnu.MPI.CUDA.ex inputs.2d.cyl_in_cartcoord
`
### Error:

> reading extern runtime parameters ...
>  EOS: small_temp cannot be less than the mintemp allowed by the EOS. Resetting small_temp to mintemp.
>  EOS: small_dens cannot be less than the mindens allowed by the EOS. Resetting small_dens to mindens.
> 
> Time in ca_set_method_params: 6.000000001e-07
> 1 Species: 
> X  
> Successfully read inputs file ... 
> Starting to call amrex_probinit ... 
> Successfully run amrex_probinit
> Initializing the data at level 0
> amrex::Error::0::Error: initial data has rho <~ small_dens !!!
>

**Comment by Jokeren** [comment] 2021-03-05 21:06
@zingale Could you please take a look?

**Comment by zingale** [comment] 2021-03-05 21:15
can you try CUDA 11.1?

I think you are hitting a bug/issue in a recent switch to how the memory is allocated when on GPUs, which changed with CUDA 11.2.

**Comment by Jokeren** [comment] 2021-03-05 21:23
Yeah I tried CUDA 11.1 but the same problem still exists. What information do you think I can provide to help you track down this error?

**Comment by zingale** [comment] 2021-03-05 21:29
okay thanks.  We'll find someone with access to an A100 to try to reproduce this.

**Comment by maxpkatz** [comment] 2021-03-05 21:33
Keren, do you see anything suspicious when running this through cuda-memcheck/compute-sanitizer?

**Comment by Jokeren** [comment] 2021-03-05 21:45
Hi Max, there does not seem to have anything suspicious. I fiddled with a few knobs such as `CUDA_HOME` and `GPU_COMPATIBLE_PROBLEM` but didn't help. Below is the full summary reported by compute-sanitizer.

> ========= COMPUTE-SANITIZER
> Initializing CUDA...
> CUDA initialized with 1 GPU
> AMReX (21.03) initialized
> 
> Starting run at 21:43:00 UTC on 2021-03-05.
> Successfully read inputs file ... 
> 
> Castro git describe: 21.03-dirty
> AMReX git describe: 21.03
> Microphysics git describe: 21.03
> 
> reading extern runtime parameters ...
>  EOS: small_temp cannot be less than the mintemp allowed by the EOS. Resetting small_temp to mintemp.
>  EOS: small_dens cannot be less than the mindens allowed by the EOS. Resetting small_dens to mindens.
> 
> Time in ca_set_method_params: 3.200000016e-07
> 1 Species: 
> X  
> Successfully read inputs file ... 
> Starting to call amrex_probinit ... 
> Successfully run amrex_probinit
> Initializing the data at level 0
> amrex::Error::0::Error: initial data has rho <~ small_dens !!!
> SIGABRT
> See Backtrace.0 file for details
> ========= Error: process didn't terminate successfully
> ========= Target application returned an error
> ========= ERROR SUMMARY: 0 errors
>

**Comment by maxpkatz** [comment] 2021-03-05 22:17
That is strange. We don't think there's anything wrong with this setup, but I also cannot explain what you're seeing. Perhaps some time we could jump on a call and you can show me what you're doing so I can attempt to debug it.

**Comment by Jokeren** [comment] 2021-03-05 23:33
No problem. To setup a call, just send me an email and copy John.

**Comment by maxpkatz** [comment] 2021-03-08 17:34
We chatted this morning and I realized that the issue is that on @Jokeren's system, the trick we're using to override `problem_initialize.H` and `problem_initialize_state_data.H` is not working, so he was getting the empty definitions of those files from `Source/problems`. I'm not sure what's different about his setup compared to our development systems that caused this trick not to work.

**Comment by maxpkatz** [comment] 2021-10-22 03:17
I'm going to close this issue, I don't believe we have seen this on any other system

**Closed by maxpkatz** 2021-10-22 03:17 UTC
